### ISSUE TITLE
Feat: Implement the project page design and functionality [large feature]

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#38]
### Description
We need to have a paginated project page where we display all the Open Source projects. When a user clicks on the projects button on the navbar, this is the page they should view. This is a large feature and multiple people can work on it. These are the tasks you should complete:

Design - https://www.figma.com/design/mALWb4e0vqfBbtRwop3g16/AFOS?node-id=2019-4439&t=IpmdXDgKlYiLWOeE-0

### Tasks
- [ ] Implement the mobile and desktop view of the project page as per the design. 
- [ ] Apply pagination - we're using Shadcn UI for pagination and creating the cards
- [ ] Create a search functionality. You can use JSON dummy data for now as we figure out the endpoint
- [ ] Include search filters functionality as per the design

### Good practice
- Implement type safety where necessary
- Ensure the mobile designs are responsive

**Comment by ozaharsh95** [comment]
@CatherineKiiru I want to contribute can you assign it to me please?

**Comment by CatherineKiiru** [comment]
Hi, @ozaharsh95 I've assigned you!

**Comment by komenAnna** [comment]
Hi @CatherineKiiru I'd love to contribute. Is there any issue I could work on? If yes, please assign me. Thanks.

**Comment by Giftea** [comment]
Hi @CatherineKiiru, Can I be assigned too? Thanks.

**Comment by CatherineKiiru** [comment]
Hi @ozaharsh95 I'd like you to work with @Giftea and @komenAnna. What sections can you collaborate on?

**Comment by ozaharsh95** [comment]
@CatherineKiiru , 

I have done pagination and view tasks but filter and search functionality are left to be implemented. 

And also the react components implemented as jsx components do we need to convert them to tsx ?

**Comment by Giftea** [comment]
> @CatherineKiiru ,
> 
> I have done pagination and view tasks but filter and search functionality are left to be implemented.
> 
> And also the react components implemented as jsx components do we need to convert them to tsx ?

Hello @ozaharsh95, can you create a PR?

**Comment by ozaharsh95** [comment]
> > @CatherineKiiru ,
> > I have done pagination and view tasks but filter and search functionality are left to be implemented.
> > And also the react components implemented as jsx components do we need to convert them to tsx ?
> 
> Hello @ozaharsh95, can you create a PR?

YES @Giftea

**Comment by CatherineKiiru** [comment]
> @CatherineKiiru ,
> 
> I have done pagination and view tasks but filter and search functionality are left to be implemented.
> 
> And also the react components implemented as jsx components do we need to convert them to tsx ?

Hi @ozaharsh95  write in jsx for now, I'll refactor it. I am refactoring the codebase to tsx

**Comment by ozaharsh95** [comment]
> > @CatherineKiiru ,
> > I have done pagination and view tasks but filter and search functionality are left to be implemented.
> > And also the react components implemented as jsx components do we need to convert them to tsx ?
> 
> Hi @ozaharsh95 write in jsx for now, I'll refactor it. I am refactoring the codebase to tsx

@CatherineKiiru Okay Thanks for guiding.

**Comment by CatherineKiiru** [comment]
@Giftea can you work on the filter and search functionality? cc @ozaharsh95

**Comment by Giftea** [comment]
> @Giftea can you work on the filter and search functionality? cc @ozaharsh95

Yes I can

**Comment by Giftea** [comment]
@ozaharsh95 Can you invite me to your [Fork](https://github.com/ozaharsh95/AFOS-AfricanOpenSource/tree/project-section-with-search-pagination)?

Email: eleojogiftuhiene@gmail.com
Username: Giftea

**Comment by ozaharsh95** [comment]
> @ozaharsh95 Can you invite me to your [Fork](https://github.com/ozaharsh95/AFOS-AfricanOpenSource/tree/project-section-with-search-pagination)?
> 
> Email: [eleojogiftuhiene@gmail.com](mailto:eleojogiftuhiene@gmail.com) Username: Giftea

yes sure

**Comment by Giftea** [comment]
@CatherineKiiru Is there a Figma prototype that demonstrates the flow of the "search filters functionality"?

**Comment by Shubhankar-1** [comment]
Hi @CatherineKiiru is there are any tasks that are not yet completed. If so, I would be happy to contribute to them. Please let me know if I can assist with any ongoing tasks or issues.

**Comment by CatherineKiiru** [comment]
> @CatherineKiiru Is there a Figma prototype that demonstrates the flow of the "search filters functionality"?

No

**Comment by CatherineKiiru** [comment]
> Hi @CatherineKiiru is there are any tasks that are not yet completed. If so, I would be happy to contribute to them. Please let me know if I can assist with any ongoing tasks or issues.

Hi @Shubhankar-1 I'll let you know once I create more issues
