### ISSUE TITLE
Create the navbar and hero section component

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#4]
### Description
Implement the Navbar and hero section as per the design. Also implement the mobile responsive design. Try to ensure the component is pixel perfect.

![Screenshot from 2023-07-18 19-13-37](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/b8fc028d-ab98-4b75-8523-a020d93bcd6f)

### Scenarios
- A user needs to view the Navbar and Hero section component as per the design
- A user can view the desktop and mobile version 

### Tasks
- [x] Implement the section as per the design
- [x] Use GitHub CoPilot for the project to generate code suggestions
- [x] Submit PR as per the contributing guidelines

**Comment by bilesanmiahmad** [comment]
Hello @CatherineKiiru I would like to work on this issue. Please can you help me with the necessary permissions

**Comment by CatherineKiiru** [comment]
Hello @bilesanmiahmad thanks for showing interests, but the issue has already worked on.
