### ISSUE TITLE
Create a newsletter section

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/GitHub-Copilot-Hackathon-Project#9]
### Description
Implement the newsletter section as per the design. Also implement the mobile responsive design. Try to implement hover states and ensure the component is pixel perfect.

![Screenshot from 2023-07-18 20-23-07](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/a1e0bd70-49d6-4d8d-9406-b608a2d716c0)

### Scenarios
- A user needs to view the newsletter section as per the design
- A user can view the desktop and mobile version
- Add hover effects to the buttons

### Tasks
- [x] Implement the section as per the design
- [x]  Use GitHub CoPilot for the project to generate code suggestions
- [x] Submit PR as per the contributing guidelines

**Comment by mihrab34** [comment]
Hi @CatherineKiiru i would like to work on this issue. Is there a design file available for this section

**Comment by mihrab34** [comment]
Never mind. I've seen the figma file.

**Comment by mihrab34** [comment]
> Never mind. I've seen the figma file.

Seen the figma file

> Hi @CatherineKiiru i would like to work on this issue. Is there a design file available for this section

Seen the figma file

**Comment by mihrab34** [comment]
> Hi @CatherineKiiru i would like to work on this issue. Is there a design file available for this section

Seen the Figma file

**Comment by CatherineKiiru** [comment]
Hi @mihrab34, great! I'll assign you the issue. Do you have access to GitHub CoPilot? You'll need to use CoPilot so we can capture accurate feedback for this project. 

Share your email address so we can give you access to CoPilot

**Comment by mihrab34** [comment]
No i do not have access to co-pilot.

**Comment by CatherineKiiru** [comment]
Hi @mihrab34, you now have access. Accept the invitation sent to your email.

**Comment by mihrab34** [comment]
Hi @CatherineKiiru  I still don't have access to the organization GitHub co-pilot. I just reloaded the extension on my VScode and I still get the same no-access error. Added a screenshot to show what I have on my end

![co-pilot](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/35562131/7b70567d-0aff-4f19-a563-b1a8b6dac963)

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 did you get an email invitation?

**Comment by mihrab34** [comment]
yes i got the collaboration invite.  I have access now. I missed the second email invite from Ruth

**Comment by CatherineKiiru** [comment]
Did you get such an invitation? If so, you should accept it

![Screenshot from 2023-08-07 16-29-24](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/66266208/b56b38f0-0e56-4549-ba88-87846bf9c6cb)

**Comment by CatherineKiiru** [comment]
> yes i got the collaboration invite. I have access now. I missed the second email invite from Ruth

Great. How long do you feel you'll need to complete this issue?

**Comment by mihrab34** [comment]
> > yes i got the collaboration invite. I have access now. I missed the second email invite from Ruth
> 
> Great. How long do you feel you'll need to complete this issue?

Hopefully before EOD tomorrow

**Comment by mihrab34** [comment]
I can't find the mobile screen for the newsletter

![chaoss](https://github.com/chaoss/GitHub-Copilot-Hackathon-Project/assets/35562131/37a4af44-1464-4d6d-ad56-8b129d3a30c0)

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 thanks for letting me know, we're working on it with the designers

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 the mobile version of the newsletter section is now ready, you can work on it. Thank you for your patience. I can also see the branch now

Check the design out:
https://www.figma.com/file/mALWb4e0vqfBbtRwop3g16/Afos?type=design&node-id=44-930&mode=design&t=Nbg6nzoa0IUHGf6A-0

**Comment by mihrab34** [comment]
> Hi @mihrab34 the mobile version of the newsletter section is now ready, you can work on it. Thank you for your patience. I can also see the branch now
> 
> Check the design out: https://www.figma.com/file/mALWb4e0vqfBbtRwop3g16/Afos?type=design&node-id=44-930&mode=design&t=Nbg6nzoa0IUHGf6A-0

done

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 thank you for the good work you've done on this project. We'd like to collect your feedback on your experience with working with GitHub CoPilot in this project. Kindly fill this form and submit by tomorrow close of business. 

https://docs.google.com/forms/d/e/1FAIpQLScMhgf8fOq1fgM5OU3xstpt_jLy_RP8rOGO3P45HYaqUBMG5A/viewform?usp=sf_link

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 are you located in Lagos? We'd like to do a video recording of your experience in using GitHub Copilot for this project. Let me know If you'd be interested in doing the recording.
